### ISSUE TITLE
edit does nothing

### ISSUE THREAD

**Issue by chovy** [Hydrothermal/better-pastebin#1]
Looks like edit is not supported by pastebin.com api.

Working on a fix for it. PR imminent....

**Comment by Hydrothermal** [comment]
Thanks for the fix. Most likely this was broken by pastebin's recent site overhaul.

**Comment by chovy** [comment]
Yeah, i figured as much. You got me 95% of the way there. I figured it was csrf issue. 

Can you publish a new version on NPM?

**Comment by Hydrothermal** [comment]
New version is published. Thanks again!

**Comment by chovy** [comment]
Awesome. thanks!

**Comment by scottie** [comment]
Edit is not working
