### ISSUE TITLE
Editing a paste resets the existing options

### ISSUE THREAD

**Issue by SoullessWaffle** [Hydrothermal/better-pastebin#4]
[The docs say](https://github.com/Hydrothermal/better-pastebin#editing-a-paste):
> If left unspecified, these [options] default to the paste's existing options.

But when I try to edit an existing paste it seems to reset all the options I don't specify:

- it resets the privacy to public
- it resets the name to "Untitled"
- it resets the format to "" (tested with the format originally set to "lua")

This is also the case if you pass only the new contents as a string.

Presumably the rest of the options such as expiration are reset as well, although I haven't tested this.

Edit: to clarify, if I supply the paste's original options object to the edit function it keeps all of them except format. I tested this with these options:
```json
{
      "anonymous": false,
      "expires": "N",
      "format": "lua",
      "privacy": "1",
      "name": "test"
}
```

**Comment by sirDonovan** [comment]
@Hydrothermal can you please publish a new version to NPM?

**Comment by Hydrothermal** [comment]
@sirDonovan New version is published.
